@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

AddressBook *-right-> "1" UniquePersonList
AddressBook *-right-> "1" UniqueLessonTimeList
UniqueLessonTimeList -[hidden]down- UniquePersonList
UniqueLessonTimeList -[hidden]down- UniquePersonList

UniqueLessonTimeList -right-> "*" LessonTime
UniquePersonList -right-> Person

Person -up-> "*" LessonTime

Person *--> Name
Person *--> Phone
Person *--> PaymentStatus
Person *--> HomeworkList
Person *--> Participation
@enduml
